collections:
  - name: "kubernetes_fundamentals"
    description: "Theoretical knowledge about Kubernetes. Contains information about the fundamentals of Kubernetes (concepts, architecture, etc.)."
    dirs:
      - "knowledge\\kubernetes\\website-main\\content\\en\\docs"
    rules:
      - include: ["*.md"]
        exclude: []
        min_length: 0
        max_length: -1
        generate_summary: false

  - name: "kubernetes_code"
    description: "Theoretical knowledge about Kubernetes. Contains information about the fundamentals of Kubernetes (concepts, architecture, etc.)."
    dirs:
      - "knowledge\\kubernetes\\website-main\\content\\en\\examples"
    rules:
      - include: ["*.yaml", "*.yml"]
        exclude: []
        min_length: 0
        max_length: -1
        generate_summary: true

  - name: "docker_fundamentals"
    description: "Theoretical knowledge about Docker. Contains information about the fundamentals of Docker (concepts, architecture, etc.)."
    dirs:
      - "knowledge\\docker\\docs-main\\content\\get-started"
      - "knowledge\\docker\\docs-main\\content\\guides"
      - "knowledge\\docker\\docs-main\\content\\manuals"
    rules:
      - include: ["*.md"]
        exclude: []
        min_length: 0
        max_length: -1
        generate_summary: false

  - name: "docker_code"
    description: "Code examples about Docker."
    dirs:
      - "knowledge\\docker\\docs-main\\content\\reference"
    rules:
      - include: ["*.md"]
        exclude: []
        min_length: 0
        max_length: -1
        generate_summary: true