answer_question:
  description: >
    Your goal is to answer a the given question abouth DevOps, with the greater possible detail.
    
    To complete the task, you should:
    
    <steps>
      1 - Analyze the question and determine the topics you need to search for, and other topics that might be related to the question,
          even if they are not directly related to the question. Ensure to make a list, to keep track of the topics you need to search for.
      2 - Search for information, using the search tools, about the question and the topics. Take in count that the question might not 
          use language and keywords, so feel free to reformulate the question to search for information, and make searches based on the
          topics you detected. If applicable, add code examples to the search and to the answer. If code examples
          are applicable ensure to use best practices and production level code examples. Feel free to use 
          different keywords and languages to search for information, and make as many searches as you need.
      3 - Summarize the information you found in a concise and detailed answer to the question, ensuring that the answer is easy to understand,
          engages in best practices and is production level, and answer the question with the greater possible detail.
      4 - Verify that the answer is correct and complete. If the is complete and meets the standards, return the answer. If not, go back to step 1
          to search for more information, and generate an improved answer.
    </steps>
    
    <task_completion_requirements>
      The final answer must be correct and complete, with best practices and production level.
      The format of the answer must be markdown, with a clear structure and easy to understand.
    </task_completion_requirements>

    <task_input>
    The question to answer is the following:
      <question>
        {query}
      </question>
    </task_input>
      
  expected_output: >
    A concise and detailed markdown, with a clear structure and easy to understand, answer to the question, with best practices and production level.
  agent: researcher    

create_k8s_config:
  description: >
    Your goal is to create a k8s config file named nginx-prod.yaml with the file 
    creation/edition tools.
    
    The config file should be a: 
    
    <description>
      production level, for nginx server. 
    </description>
    
    <requirements>
      Nginx should be accessible for users in port 5010 through an load balancer. 
    </requirements>

    To complete the task, you should:
    
    <steps>
      1 - Analyze the goal of the task and the requirements.
      2 - Search for information about k8s config files and requirements for the required config file.
      3 - Use the file creation/edition tools to create the config file.
          Ensure to include comments in the config file to explain the choices made
          and make it easier to understand.
      4 - Validate the config file using the config validator tool.
      4.1 - If the config file is not valid, analyze the issues found, search 
          for information about the issues found and reason about them and 
          the possible solutions. Then go back to step 3 to fix the issues found.
          The security scan is the most important issue to fix, then the yaml syntax
          that would cause the config file to be invalid then the rest of the issues.
      4.2 - If the config file is valid, continue to the next step.
      5 - Return a summary of the task.
    </steps>

    To complete the task, you should:
    
    <task_completion_requirements>
      Have a valid k8s config file named nginx-prod.yaml, with the latest updates.
      Before finishing, the file requires to be validated using the config validator tool.
      The final summary should must include (if any) the non-solved issues found.
    </task_completion_requirements>
      
  expected_output: >
    A created/edited k8s config file named nginx-prod.yaml, with the latest updates and comments
    explaining the choices made. 
    
    Also, the final summary should must include (if any) the non-solved issues found.
  agent: researcher