analyse_manifest_issue:
  description: >
    **Goal - pinpoint and plan the fix**  
    Examine the failing manifest, identify root-cause(s) of the validation
    errors, and sketch a *minimal* change set that yields a functional
    Kubernetes object (security hardening out-of-scope).

    **Scope & rules**

    • Triage **one file per run** - the path is inferred from the first stack-
      trace or the `file:` entry inside `<issues>`.  
    • Error details live in `<issues>`; clear them before touching stylistic
      nits.  
    • If spec ambiguity or conflicting best practices arise, *pause once* to
      query **devops_researcher** (for example: unknown `apiVersion`, 
      deprecated field, incompatible selector).  
    • Validation targets functional readiness only - ignore PSP/PSS, CIS,
      image-signing, etc.

    **Execution workflow**

    1. **Parse** - read file & error; highlight offending YAML keys/values.  
    2. **Diagnose** - map each error to its cause (schema, typo, missing field
       or wrong kind) and cite the relevant doc line.  
    3. **Resolve gaps** - if the fix requires domain knowledge (e.g.,
       `RollingUpdate` strategy default), ask **devops_researcher**; otherwise
       apply the *smallest viable* default and record why. As Iterations increase,
       increase the consults to the researcher, looking for the minimal viable
       default.
    4. **Propose fix** - list exact field edits (add / replace / delete).  
    5. **Radical fix** - in case that iterations goes over 5, and a persistent issue is found, 
    in the records, apply redical changes, ignoring best-practice and security, in order
    to ensure that the issue is fixed.
    6. **Report** - deliver root-cause, proposed YAML diffs (in prose),
       researcher Q-&-A, and rationale.
       

    **Context Blocks**

    • `<issues>` - Last validation error output.  
    • `<blackboard>` - Project-wide artefacts and notes.  
    • `<feedback>` - If present, addressing it is top priority.


    <issues>
    {issues}
    </issues>

    <blackboard>
    {blackboard}
    </blackboard>

    <feedback>
    {feedback}
    </feedback>
  markdown: true
  expected_output: >
    • Root-cause explanation  
    • Proposed YAML changes (plain text, no code block)  
    • Any question sent to **devops_researcher** + summary answer  
    • Justification for each default
  max_retries: 3
  agent: devops_engineer

apply_manifest_fix:
  description: >
    **Goal - edit, lint, repeat until clean**  
    Apply the agreed fixes, run validation (security scan disabled), and exit
    only after the manifest passes with zero functional errors.

    **Execution workflow**

    1. **Edit file** - use `edit_file` (or `create_file` if missing) to apply
       each change described in *analyse_manifest_issue*.  
    2. **Validate** -  
       a. Run config validation tool {security_scan:false}
       b. If validation fails, patch and re-validate.  
       c. After **three** failed loops or a brand-new error class, *escalate to
          **devops_researcher*** with the fresh error payload.  
    3. **Success** - final action **must** be a passing
       `validate_manifest  {security_scan:false}` call.

    **Important**  
    The YAML edit **is mandatory**. The final action must be a successful
    validation call.

    **Context Blocks**
    • `<issues>` - Last validation error output.  
    • `<blackboard>` - Updated project state.  
    • `<feedback>` - If present, address first.

    <issues>
    {issues}
    </issues>

    <blackboard>
    {blackboard}
    </blackboard>

    <feedback>
    {feedback}
    </feedback>
  expected_output: >
    Tool calls in the form:  
    `Action: edit_file  Action_Inputs: { ... }`  
    … followed by  
    `Action: validate_manifest  Action_Inputs: { security_scan: false }`  
    The last validation must succeed.
  max_retries: 3
  agent: devops_engineer

log_manifest_fix:
  description: >
    **Goal - record the fix journey**  
    Capture a short, engineer-readable timeline of the issue, the patch, and
    the clean validation result for future audits.

    During this step **no tools may be invoked**.

  expected_output: >
    4-6 sentence plain-text log that includes:  
    • Brief error synopsis & root cause  
    • Notable YAML changes  
    • Validation success statement  
    • Any open caveats / next follow-ups
  max_retries: 3
  context:
    - analyse_manifest_issue
    - apply_manifest_fix
  agent: devops_engineer
