preliminary_structure:
  description: >
    **Goal**  
    Create a *manifest blueprint* for the single environment following the "Advanced Plan".  
    For every Kubernetes YAML file to be authored, list:
      • its repository-relative path (file_path)
      • the namespace to which the element will belong (namespace)
      • a short paragraph with the description of the manifest's purpose (description).

    **Methodology**

    1. Consolidate inputs from the blackboard, and the
       previous tasks to identify all workloads and supporting resources
       required for a functional test deployment.  
    2. Adopt the define project structure directory layout. Overlays are intentionally omitted.  
    3. Where information is missing, consult **devops_researcher** or apply the
       “smallest viable production default,” justifying the fallback in one phrase.

    <blackboard>
    {blackboard}
    </blackboard>

    <feedback>
    {feedback}
    </feedback>
  expected_output: >
    Narrative prose or structured Markdown—**no YAML/JSON/code blocks**—listing
    for *each* manifest:  
    • file path  • namespace   • description.  
    Use concrete, non-generic wording; omit tags, registries, versions, and
    implementation minutiae. Another senior engineer should be able to model the
    cluster without further clarification.

    Ensure to do not include duplicated functions in the manifests.

    The output NEEDS to be the plain text, not a markdown document, and not a reference
    tp a previous file. The last answer is the report integrally.
  max_retries: 3
  agent: devops_researcher

structured_preliminary_structure:
  description: >
    **Goal**  
    Produce the *authoritative manifest index* for the test environment in
    machine-readable form. Include only YAML files in the index.

    **Methodology**

    1. Transform the vetted output of **preliminary_structure** into a strict
       JSON data set.  
    2. Ensure that all the required information is present to model the cluster.
    3. Return the JSON array—and nothing else.

    <blackboard>
    {blackboard}
    </blackboard>

    <feedback>
    {feedback}
    </feedback>
  expected_output: >
    A single JSON array where every element has the following keys:  
    • **file_path** (string) repository-relative YAML file name  
    • **namespace** (string) Kubernetes namespace  (if the manifest does not belong to any namespace, use "N/A")
    • **description** (string) succinct description  

    Ensure to do not include duplicated functions in the manifests.

  max_retries: 3
  agent: devops_researcher
