research_k8s_config:
  description: >
    Your goal is to research all the required information required for the devops_engineer be able to create a 
    k8s config file, that meets the requirements of the task.
    
    To complete the task, you should:
    
    <steps>
      1 - Analyze the goal of the task and the requirements.
      2 - Use all the tools available to research a get a report with all the required information about the task
      that the devops_engineer needs to create a k8s config file.
      3 - Return a detailed report with all the required information about the task, in markdown format.
    </steps>
    
    a proper report should include:
    <report_requirements>
    - A summary of the task, with technical details and information.
    - A comprehensive description, with technical details and information, and code examples when apply, of the 
    resources that might be relevant for the task. Also include information that might not be for the resources
    mentioned but might be relevant for the task.
    </report_requirements>

    <important>
    - To use the tools available, use the proper way to use them, with Action and Action Input.
    </important>

    The task to be completed is the following:
    <task>
     {task}
    </task>
  expected_output: >
    A summary of the task, in markdown format, that includes detailed information about the resources to be used, 
    a comprehensive description, with technical details and information, and code examples when apply, of the 
    resources that might be relevant for the task. Also include information that might not be for the resources
    mentioned but might be relevant for the task.
  markdown: true
  max_retries: 3
  agent: devops_researcher

research_image_data:
  description: >
    The task, is to retrieve all the required information about the images to be used to complete the given task.
    Ensure to retrieve the latest stable tag to be used, the repository to be used, the digest to get the image details,
    relevant information about ports, volumes, environment variables and any other relevant information that might result
    relevant for the task and the pullable digest. 

    The preferred order to retrieve the information is the following:
    1 - Retrieve docker manifest of the latest stable tag to be used.
    2 - Retrieve image details using the digest retrieved in step 1, to get relevant information about ports, volumes, environment variables and any other relevant information that might result
    3 - Retrieve the pullable digest to be used to pull the image.
    relevant for the task.


    <important>
    - Ensure to select the pullable digest to be used to pull the image, otherwise the image will not be pullable and the
    task will fail.
    </important>

    The task to be completed is the following:
    <task>
     {task}
    </task>
  expected_output: >
    A json output, that includes the latest stable tag to be used, the repository to be used, the digest, relevant information  
    about ports, volumes, environment variables and any other relevant information that might result relevant 
    for the task.
  max_retries: 3
  agent: devops_researcher

create_k8s_config:
  description: >
    Your goal is to complete the given devops task, with production level, best practices and security in mind.
    
    The task to be completed is the following:
    <task>
     {task}
    </task>

    The full configuration,regarless of the task, should be defined in only one file.

    To complete the task, you should:
    
    <steps>
      1 - Analyze the goal of the task and the requirements.
      2 - If required, request more information to the devops_researcher agent 
      about k8s config files, images to be used, and requirements for the required config file.
      3 - Use the file creation/edition tools to create the config file.
          Ensure to include comments in the config file to explain the choices made
          and make it easier to understand.
      4 - Validate the config file using the config validator tool.
      4.1 - If the config file is not valid, analyze the issues found, search 
          for information about the issues found and reason about them and 
          the possible solutions. Then go back to step 3 to fix the issues found.
          The security scan is the most important issue to fix, then the yaml syntax
          that would cause the config file to be invalid then the rest of the issues.
      4.2 - If the config file is valid, continue to the next step.
      5 - Return a summary of the task.
    </steps>

    To complete the task, you should:
    
    <task_completion_requirements>
      Have a valid k8s config file, with the latest updates.
      Before finishing, the file requires to be validated using the config validator tool.
      The final summary should must include (if any) the non-solved issues found.
    </task_completion_requirements> 
    
    <important>
    - Remember that will work over a Kind empty cluster, so the order in which the resources are created is important.
    for example, a new namespace should be created before a new deployment.
    - Enure that the non-resolved issues found are not critical for the task to be completed, and that left only because
    it is not possible to fix them with the tools available.
    - To use the tools available, use the proper way to use them, with Action and Action Input.
    </important> 
  expected_output: >
    A created/edited k8s config file, with the latest updates and comments
    explaining the choices made. 
    
    Also, a json output, should must include a with the paths of the created files, a little summary of what 
    the configuration does, and a list of the non-solved issues found with explanations.
  max_retries: 3
  context: 
    - research_k8s_config
    - research_image_data
  agent: devops_engineer
