test_k8_configuration_kubectl:
  description: >
    You will verify that the k8s configuration applied in the cluster is working as expected.
    
    To complete the task, you should:
    
    <steps>
      1 - Using get state, logs, and description of the elements in the cluster, verify that the configuration 
      is working as expected.
      2 - If required, read the configuration file and the k8s cluster to understand the configuration.
      3 - If required, request more information to the devops_researcher agent about the configuration 
      file and the required commands to test it.
      4 - Return a summary of the task, in markdown format, with all the issues found, with all the 
      details you can get.
    </steps>

    To complete the task, you should:
    
    <task_completion_requirements>
      Have a detailed analysis of the k8s configuration tested.
    </task_completion_requirements>      
    
    <important>
    - To use the tools available, use the proper way to use them, with Action and Action Input.
    </important>

    The state contains the available information until the current point, use it to complete the task.
    
    <state>
      {state}
    </state>
  expected_output: >
    A summary of the task, in markdown format, specifying that this is the kubectl scan report, with all the issues found, with all the details 
    you can get. 
  async_execution: true
  markdown: true
  max_retries: 3
  agent: devops_tester

test_k8_configuration_popeye:
  description: >
    You will verify that the k8s configuration applied in the cluster is working as expected.
    
    To complete the task, you should:
    
    <steps>
      1 - Using popeye scan, verify that the configuration is working as expected.
      2 - If required, read the configuration file and the k8s cluster to understand the configuration.
      3 - If required, request more information to the devops_researcher agent about the configuration 
      file and the required commands to test it.
      4 - Return a summary of the task, in markdown format, with all the issues found, with all the 
      details you can get.
    </steps>

    To complete the task, you should:
    
    <task_completion_requirements>
      Have a detailed analysis of the k8s configuration tested.
    </task_completion_requirements>      
    
    <important>
    - To use the tools available, use the proper way to use them, with Action and Action Input.
    </important>

    The state contains the available information until the current point, use it to complete the task.
    
    <state>
      {state}
    </state>
  expected_output: >
    A summary of the task, specifying that this is the popeye scan report, in markdown format, with all the issues found, with all the details 
    you can get. 
  async_execution: true
  max_retries: 3
  markdown: true
  agent: devops_tester

test_k8_configuration_report:
  description: >
    Using the report generated by the popeye scan and the kubectl command tool that you will receive as context, create a comprehensive report
    of the configuration tested, with all the issues found and the details you can get, ordered by severity.  

    The severity levels are:
    - low
    - medium
    - high
    - very_high

    The low severity issues are not critical and can be ignored. With this issues, the cluster functionality is not affected.
    The medium severity issues are critical and should be fixed. With this issues, the cluster functionality is not affected.
    The high severity issues are critical, representing security and/or stability issues and should be fixed. With this issues, the cluster functionality is not affected. 
    The very_high severity issues are critical ones that prevents the cluster from working as expected.

    Also, include in the report if, regardless of the issues found, the cluster is working as expected or not.     

    You can use any of the available tools to get deeper information about the issues found if the information 
    is not enough.   

    <important>
    - To use the tools available, use the proper way to use them, with Action and Action Input.
    </important>

    The state contains the available information until the current point, use it to complete the task.
    
    <state>
      {state}
    </state>
  expected_output: >
    A comprehensive report of the configuration tested, with all the issues found, with all the details 
    you can get, ordered by severity and if the cluster is working as expected or not. Any recommendations
    to solve each issue found should be included if possible.
  max_retries: 3
  agent: devops_tester
  context:
    - test_k8_configuration_popeye
    - test_k8_configuration_kubectl