research_k8s_testing:
  description: >
    Your goal is to research all the required information required for the devops_tester be able to test a 
    k8s config file, and verify that it works as expected.
    
    To complete the task, you should:
    
    <steps>
      1 - Analyze the goal of the task and the requirements.
      2 - Use all the tools available to research a get a report with all the required information about the task
      that the devops_tester needs to test a k8s config file.
      3 - Return a detailed report with possible options, commands, metrics and logs to verify if the k8s config file
      is working as expected.
    </steps>
    
    a proper report should include:
    <report_requirements>
    - A summary of the task, with technical details and information.
    - Detailed information about the the tests to be made, previous requirements to test the k8s config file and any other relevant information.
    - A comprehensive description, with technical details and information, and code examples when apply.
    </report_requirements>

    <important>
    - To use the tools available, use the proper way to use them, with Action and Action Input.
    </important>
  expected_output: >
    A summary of the task, in markdown format, that includes detailed information about about the tests to be made,
    previous requirements to test the k8s config file and any other relevant information.
  markdown: true
  max_retries: 3
  agent: devops_researcher

test_k8_configuration:
  description: >
    You will test the devops configuration file created by the devops_engineer agent and ensure it is working as expected.
    
    To complete the task, you should:
    
    <steps>
      1 - Read and understand the configuration file.
      2 - If required, request more information to the devops_researcher agent about the configuration 
      file and the required commands to test it.
      3 - Clear the kubernetes cluster.
      4 - Apply the configuration file.
      5 - Verify the configuration is correctly working.
      6 - In case of any issue, analyze the issue and search for information about the issue and reason about it,
      and request the devops_engineer agent to fix the issue and go back to step 1. If no issue is found, 
      continue to step 7.
      7 - Clear the kubernetes cluster.
      8 - Return a summary of the task, in markdown format, with the path of the configuration file tested,
      a little summary of the actions taken during the task, a list of the tests implemented, and 
      the results of the tests.
    </steps>

    To complete the task, you should:
    
    <task_completion_requirements>
      Have a valid and tested k8s config file.
    </task_completion_requirements>      
    
    <important>
    - To use the tools available, use the proper way to use them, with Action and Action Input.
    </important>
  expected_output: >
    A summary of the task, in markdown format, with the paths of the configuration files tested,
    a little summary of the actions taken during the task, a list of the tests implemented, and 
    the results of the tests. 
  guardrail: Ensure that the answers contents the paths of the configuration files tested,
    a little summary of the actions taken during the task, a list of the tests implemented, and 
    the results of the tests.
  max_retries: 3
  context: 
    - create_k8s_config
    - research_k8s_testing
  agent: devops_tester