research_k8s_config:
  description: >
    Your goal is to research all the required information required for the devops_engineer be able to create a 
    k8s config file, that meets the requirements of the task.
    
    To complete the task, you should:
    
    <steps>
      1 - Analyze the goal of the task and the requirements.
      2 - Use all the tools available to research a get a report with all the required information about the task
      that the devops_engineer needs to create a k8s config file.
      3 - Return a detailed report with all the required information about the task, in markdown format.
    </steps>
    
    a proper report should include:
    <report_requirements>
    - A summary of the task, with technical details and information.
    - A comprehensive description, with technical details and information, and code examples when apply, of the 
    resources that might be relevant for the task. Also include information that might not be for the resources
    mentioned but might be relevant for the task.
    </report_requirements>

    <important>
    - To use the tools available, use the proper way to use them, with Action and Action Input.
    </important>

    The state contains the available information until the current point, use it to complete the task.
    
    <state>
      {state}
    </state>
  expected_output: >
    A summary of the task, in markdown format, that includes detailed information about the resources to be used, 
    a comprehensive description, with technical details and information, and code examples when apply, of the 
    resources that might be relevant for the task. Also include information that might not be for the resources
    mentioned but might be relevant for the task.
  markdown: true
  max_retries: 3
  async_execution: true
  agent: devops_researcher

create_k8s_config:
  description: >
    Your goal is to complete the given devops task, with a production level, high availability, configuration, but 
    focused on simplicity and ease of use.
    
    The full configuration,regarless of the task, should be defined in only one file.

    To complete the task, you should:
    
    <steps>
      1 - Analyze the goal of the task and the requirements.
      2 - If required, request more information to the devops_researcher agent 
      about k8s config files, images to be used, and requirements for the required config file.
      3 - Use the file creation/edition tools to create the config file.
          Ensure to include comments in the config file to explain the choices made
          and make it easier to understand.
      4 - Validate the config file using the config validator tool WITHOUT the security scan enabled.   
      4.1 - If the config file is not valid, analyze the issues found classify them using the follow scale:
      
      The severity levels are:
      - low
      - medium
      - high
      - very_high

      The low severity issues are not critical and can be ignored. With this issues, the cluster functionality is not affected.
      The medium severity issues are critical and should be fixed. With this issues, the cluster functionality is not affected.
      The high severity issues are critical, representing security and/or stability issues and should be fixed. With this issues, the cluster functionality is not affected. 
      The very_high severity issues are critical ones that prevents the cluster from working as expected.
      
      Then search for information about the issues found, and reason about the possible solutions.
      
      Then go back to step 3 to fix the issues found. The yaml syntax issues
      that would cause the config file to be invalid then the rest of the issues.
      Use the severity level to prioritize the issues to fix.
      
      4.2 - If the config file is valid, continue to the next step.
      5 - Return a summary of the task.
    </steps>

    To complete the task, you should:
    
    <task_completion_requirements>
      Have a valid k8s config file, with the latest updates.
      Before finishing, the file requires to be validated using the config validator tool.
      The final summary should must include (if any) the non-solved issues found.
    </task_completion_requirements> 
    
    <important>
    - Remember that will work over a Kind empty cluster, so the order in which the resources are created is important.
    for example, a new namespace should be created before a new deployment.
    - Enure that the non-resolved issues found are not critical for the task to be completed, and that left only because
    it is not possible to fix them with the tools available.
    - To use the tools available, use the proper way to use them, with Action and Action Input.
    </important> 

    Some best practices to follow:
    <best_practices>
    - Use a namespace to isolate the resources created.
    - Always include at the begining the namespace to be used.
    - Do not use the latest stable tag, instead use the pullable digest to pull the image, or in its absence, 
    use the latest stable tag by specifying the tag name.
    </best_practices>

    The state contains the available information until the current point, use it to complete the task.
    
    <state>
      {state}
    </state>
  expected_output: >
    A created/edited k8s config file, with the latest updates and comments
    explaining the choices made. 
    
    Also, a json output, should must include a with the paths of the created files
     and a list of the non-solved issues found with explanations. If the config validator tool was not executed, 
     the list of non-solved issues should be empty. If no issues were found, add an element with the issue 
     "No issues found" and the severity "low".
  max_retries: 3
  context: 
    - research_k8s_config
    
  agent: devops_engineer
