# syntax=docker/dockerfile:1
FROM ghcr.io/tbxark/mcp-proxy:latest     

# --- Install Docker CLI and tini (no daemon) this is required to run the mcp-filesystem-server, to execute docker commands in the daemon from the mcp-proxy---
RUN apt-get update -qq \
 && apt-get install --no-install-recommends -y docker.io tini \
 && rm -rf /var/lib/apt/lists/*

# --- Network & socket wiring ---
EXPOSE 9000
VOLUME ["/var/run/docker.sock"]

ENTRYPOINT ["/usr/bin/tini","--","/main","--config","/config/config.json"]
