---  
services:  
  # ──────────────────────────────────────────────
  # Weviate Vector DB
  # ──────────────────────────────────────────────
  weaviate:  
    command:  
    - --host  
    - 0.0.0.0  
    - --port  
    - '8080'  
    - --scheme  
    - http  
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.1  
    ports:  
    - 8080:8080  
    - 50051:50051  
    volumes:  
    - weaviate_data:/var/lib/weaviate  
    restart: on-failure:0  
    environment:  
      QUERY_DEFAULTS_LIMIT: 25  
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: '${WEAVIATE_API_KEY}'
      AUTHENTICATION_APIKEY_USERS: 'user-a'
      AUTHORIZATION_RBAC_ENABLED: 'true'
      AUTHORIZATION_RBAC_ROOT_USERS: 'user-a'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
    
  mcp-proxy:
    build: 
      context: .
      dockerfile: dockerfile.mcp_proxy_with_docker
    container_name: mcp-proxy
    ports:
      - "9000:9000"            # expose public API
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/mcp_server/config.json:/config/config.json:ro # Config file at a relative path with ./
    restart: on-failure:0


volumes:  
  weaviate_data: