collections:
  - name: "kubernetes_fundamentals"
    description: "Theoretical knowledge about Kubernetes. Contains information about the fundamentals of Kubernetes (concepts, architecture, etc.)."
    dirs:
      - "knowledge\\kubernetes\\website-main\\content\\en\\docs"
    rules:
      include: ["md"]
      exclude: []
      min_length: 0
      max_length: -1
      generate_summary: false

  - name: "kubernetes_fundamentals"
    description: "Theoretical knowledge about Kubernetes. Contains information about the fundamentals of Kubernetes (concepts, architecture, etc.)."
    dirs:
      - "knowledge\\kubernetes\\kubernetes-lab-tutorial-master\\content"
    rules:
      include: ["md"]
      exclude: [] 
      min_length: 0
      max_length: -1
      generate_summary: false

  - name: "kubernetes_fundamentals"
    description: "Theoretical knowledge about Kubernetes. Contains information about the fundamentals of Kubernetes (concepts, architecture, etc.)."
    dirs:
      - "knowledge\\kubernetes\\kubernetes-the-hard-way-master\\docs"
    rules:
      include: ["md"]
      exclude: []
      min_length: 0
      max_length: -1
      generate_summary: false

  - name: "kubernetes_code"
    description: "Theoretical knowledge about Kubernetes. Contains information about the fundamentals of Kubernetes (concepts, architecture, etc.)."
    dirs:
      - "knowledge\\kubernetes\\website-main\\content\\en\\examples"
    rules:
      include: ["yaml", "yml"]
      exclude: []
      min_length: 0
      max_length: -1
      generate_summary: true

  - name: "kubernetes_checkov_problems"
    description: "Descriptions and solutions for problems found by Checkov in the Kubernetes code. Inlcudes de ID of the problem, the description, the severity and the solution."
    dirs:
      - "knowledge\\checkov\\prisma-cloud-docs\\en\\enterprise-edition\\policy-reference\\kubernetes-policies\\kubernetes-policy-index"
    rules:
      include: ["adoc"]
      exclude: []
      min_length: 0
      max_length: -1
      generate_summary: false

  - name: "kubernetes_code"
    description: "Theoretical knowledge about Kubernetes. Contains information about the fundamentals of Kubernetes (concepts, architecture, etc.)."
    dirs:
      - "knowledge\\kubernetes\\kubernetes-lab-tutorial-master\\examples"
    rules:
      include: ["yaml", "yml"]
      exclude: []
      min_length: 0
      max_length: -1
      generate_summary: true


  - name: "docker_fundamentals"
    description: "Theoretical knowledge about Docker. Contains information about the fundamentals of Docker (concepts, architecture, etc.)."
    dirs:
      - "knowledge\\docker\\docs-main\\content\\get-started"
      - "knowledge\\docker\\docs-main\\content\\guides"
      - "knowledge\\docker\\docs-main\\content\\manuals"
    rules:
      include: ["md"]
      exclude: []
      min_length: 0
      max_length: -1
      generate_summary: false

  - name: "docker_code"
    description: "Code examples about Docker."
    dirs:
      - "knowledge\\docker\\docs-main\\content\\reference"
    rules:
      include: ["md"]
      exclude: []
      min_length: 0
      max_length: -1
      generate_summary: true

  - name: "docker_checkov_problems"
    description: "Descriptions and solutions for problems found by Checkov in the Docker code. Inlcudes de ID of the problem, the description, the severity and the solution."
    dirs:
      - "knowledge\\checkov\\prisma-cloud-docs\\en\\enterprise-edition\\policy-reference\\docker-policies\\docker-policy-index"
    rules:
      include: ["adoc"]
      exclude: []
      min_length: 0
      max_length: -1
      generate_summary: false