create_k8s_config:
  description: >
    Your goal is to create a k8s config file named nginx-prod.yaml with the file 
    creation/edition tools.
    
    The config file should be a: 
    
    <description>
      production level, for nginx server. 
    </description>
    
    <requirements>
      Nginx should be accessible for users in port 5010 through an load balancer. 
    </requirements>

    To complete the task, you should:
    
    <steps>
      1 - Analyze the goal of the task and the requirements.
      2 - Search for information about k8s config files and requirements for the required config file.
      3 - Use the file creation/edition tools to create the config file.
          Ensure to include comments in the config file to explain the choices made
          and make it easier to understand.
      4 - Validate the config file using the config validator tool.
      4.1 - If the config file is not valid, analyze the issues found, search 
          for information about the issues found and reason about them and 
          the possible solutions. Then go back to step 3 to fix the issues found.
          The security scan is the most important issue to fix, then the yaml syntax
          that would cause the config file to be invalid then the rest of the issues.
      4.2 - If the config file is valid, continue to the next step.
      5 - Return a summary of the task.
    </steps>

    To complete the task, you should:
    
    <task_completion_requirements>
      Have a valid k8s config file named nginx-prod.yaml, with the latest updates.
      Before finishing, the file requires to be validated using the config validator tool.
      The final summary should must include (if any) the non-solved issues found.
    </task_completion_requirements>
      
  expected_output: >
    A created/edited k8s config file named nginx-prod.yaml, with the latest updates and comments
    explaining the choices made. 
    
    Also, the final summary should must include (if any) the non-solved issues found.
  agent: config_coder