create_k8s_config:
  description: >
      Design a k8s config file name nginx-prod.yaml, production level, for nginx server. 
      Nginx should be accessible for users in port 5010 through an load balancer. 
      Use stable image of nginx, from the official repository. 
      
      Follow the next steps: 
        1. Make a Rag query to search for definitions, best practices and code examples for production level k8s config files. 
        2. Design and write the config file.
        3. Check it with config_validator_tool:
        4. If it is not valid, use Rag to search for information about the problems found and use the edit tool to fix the problems found and go to step 3.
        5. If it is valid, justify the choices made.
  expected_output: >
    A k8s config file name nginx-prod.yaml, production level, for nginx server.
  agent: config_coder